export const LOOTERY_ETH_ADAPTER_ABI = [
  {
    "inputs":[{
      "internalType":"address payable",
      "name":"_wrappedTokenAddress",
      "type":"address"
    }],
    "stateMutability":"nonpayable",
    "type":"constructor"
  },
  {
    "name":"JackpotSeeded",
    "type":"event",
    "anonymous":false,
    "inputs":[
      {
        "indexed":true,
        "internalType":"address",
        "name":"whomst",
        "type":"address"
      },
      {
        "indexed":false,
        "internalType":"uint256",
        "name":"amount",
        "type":"uint256"
      }
    ]
  },
  {
    "name":"purchase",
    "outputs":[],
    "stateMutability":"payable",
    "type":"function",
    "inputs":[
      {
        "internalType":"address payable",
        "name":"looteryAddress",
        "type":"address"
      },
      {
        "internalType":"struct ILootery.Ticket[]",
        "name":"tickets",
        "type":"tuple[]",
        "components":[{
          "internalType":"address",
          "name":"whomst",
          "type":"address"
        },
        {
          "internalType":"uint8[]",
          "name":"pick",
          "type":"uint8[]"
      }],
    },
    {
      "internalType":"address",
      "name":"beneficiary",
      "type":"address"
    }]
    },
    {
      "name":"seedJackpot",
      "outputs":[],
      "stateMutability":"payable",
      "type":"function",
      "inputs":[
        {
          "internalType":"address payable",
          "name":"looteryAddress",
          "type":"address"
        }
      ],
    },
    {
    "inputs":[],
    "name":"wrappedToken",
    "stateMutability":"view",
    "type":"function",
    "outputs":[
      {
        "internalType":"contract IWETH9",
        "name":"",
        "type":"address"
      }
    ],
}] as const;
